config/routes.rb
Rails.application.routes.draw do
  resources :snapdbs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
   root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/snapdb.rb
class Snapdb < ApplicationRecord
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/snapdbs_controller.rb
class SnapdbsController < ApplicationController
  before_action :set_snapdb, only: %i[ show edit update destroy ]

  # GET /snapdbs or /snapdbs.json
  def index
    @snapdbs = Snapdb.all
  end

  # GET /snapdbs/1 or /snapdbs/1.json
  def show
  end

  # GET /snapdbs/new
  def new
    @snapdb = Snapdb.new
  end

  # GET /snapdbs/1/edit
  def edit
  end

  # POST /snapdbs or /snapdbs.json
  def create
    @snapdb = Snapdb.new(snapdb_params)

    respond_to do |format|
      if @snapdb.save
        format.html { redirect_to snapdb_url(@snapdb), notice: "Snapdb was successfully created." }
        format.json { render :show, status: :created, location: @snapdb }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @snapdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snapdbs/1 or /snapdbs/1.json
  def update
    respond_to do |format|
      if @snapdb.update(snapdb_params)
        format.html { redirect_to snapdb_url(@snapdb), notice: "Snapdb was successfully updated." }
        format.json { render :show, status: :ok, location: @snapdb }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @snapdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snapdbs/1 or /snapdbs/1.json
  def destroy
    @snapdb.destroy

    respond_to do |format|
      format.html { redirect_to snapdbs_url, notice: "Snapdb was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snapdb
      @snapdb = Snapdb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def snapdb_params
      params.require(:snapdb).permit(:title, :color, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snapdbs_helper.rb
module SnapdbsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container-sm"><%= yield %></div>
    
  </body>
</html>

app/views/main/index.html.erb
<h1>Hola mundo</h1>

app/views/snapdbs/_form.html.erb
<%= form_with(model: snapdb) do |form| %>
  <% if snapdb.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(snapdb.errors.count, "error") %> prohibited this snapdb from being saved:</h2>

      <ul>
        <% snapdb.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image, class:"form-control", accept:"image/*", capture:"camara" %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.color_field :color %>
  </div>

  <div>
    <%= form.submit "Guardar snapdb", class:"btn btn-primary d-block w-100" %>
  </div>
<% end %>

app/views/snapdbs/_snapdb.html.erb
<div id="<%= dom_id snapdb %>" class="snapdb" style="background-color: <%= snapdb.color%>">
  <%= image_tag url_for(snapdb.image) if snapdb.image.attached? %>
  <p>
    <%= snapdb.title %>
  </p>
</div>

app/views/snapdbs/edit.html.erb
<h1>Editing snapdb</h1>

<%= render "form", snapdb: @snapdb %>

<br>

<div>
  <%= link_to "Show this snapdb", @snapdb %> |
  <%= link_to "Back to snapdbs", snapdbs_path %>
</div>

app/views/snapdbs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Snaps - Practicando Ruby on Rails</h1>

<div id="snapdbs">
  <% @snapdbs.each do |snapdb| %>
    <%= render snapdb %>
    <p>
      <%= link_to "Show this snapdb", snapdb %>
    </p>
  <% end %>
</div>

<%= link_to "New snapdb", new_snapdb_path %>

app/views/snapdbs/new.html.erb
<h1>New snapdb</h1>

<%= render "form", snapdb: @snapdb %>

<br>

<div>
  <%= link_to "Back to snapdbs", snapdbs_path %>
</div>

app/views/snapdbs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @snapdb %>

<div>
  <%= link_to "Edit this snapdb", edit_snapdb_path(@snapdb) %> |
  <%= link_to "Back to snapdbs", snapdbs_path %>

  <%= button_to "Destroy this snapdb", @snapdb, method: :delete %>
</div>